module.exports = {
  up: (queryInterface, Sequelize) => queryInterface.bulkInsert('Client', [
    {
      id: 1,
      name: 'Client 1',
      about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p><span style="font-size: 16px;">Our client is the preferred financing partner in supporting Vehicle/COE Financing, floor stocking, equipment financing, accounts receivable financing/factoring, loans for industrial/commercial property and property development, renovation loans, and other forms of commercial lending. They are planning to steadily expand their range of financial services to cater for more of customer’s financing needs.</span></p>\n<p><span style="font-size: 16px;">They are looking for a Full-stack developer that will be able to develop and support existing applications. The main scope of work will include everything from back-end to client-side code, using optimal and efficient technologies, frameworks, and patterns. Therefore, it’s essential that you are skilled at problem solving, solution design, and high-quality coding.</span></p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 2,
      name: 'Client 2',
      about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p>Our client has a vision of a destination without obstacles, and our mission is to create roads that provide both consumers and vendors the most seamless and efficient way there. They create outstanding platforms that will set the standard for the pregnancy and motherhood industry, and shape the way pregnant mothers shop in Singapore. </p>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 3,
      name: 'Client 3',
      about: '<h3><span style="font-size: 16px;"><strong>b. About our client:</strong></span></h3>\n<p>Our client is a Tech Gaming company primarily focused on developing and creating new and innovative internet games and experiences for the Asian markets. The company creates popular online games and provide them in Asian markets where they aim to be a market leader. They are currently in the development phrase for the launch of their new online gaming platform in early 2021.</p>\n<p>They plan to continuously develop cutting edge games and technologies in this space to become the largest innovative online gaming provider in the region. They are looking for an enthusiastic designer who is keen to explore the newest technologies in the online gaming space to help them achieve this vision.</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 4,
      name: 'Client 4',
      about: '<p><strong>b. About Client:</strong></p>\n<p>Originally founded in Silicon Valley in 2014 and headquartered in Singapore, our client is a a leading digital wallet service in Southeast Asia Region, where consumers can easily purchase, sell and secure assets like Ethereum, Bitcoin and Litecoin, etc. Their goal is to serve Asia.</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 5,
      name: 'Client 5',
      about: '<p><strong>b. About our client:</strong></p>\n<p>Our client is the first and only multimedia platform in the world that enables A-List celebrities from all genres (Actors, musicians, magicians, athletes, comedians, politicians, successful entrepreneurs, entertainers, influencers, visionaries and inspirational figures) to monetize their fanbase by connecting them directly to their true fans via video. While platforms such as Youtube, Twitter and Instagram showed the world the power of influencer and social networks, by nature they are highly ineffective as a 2-way communication medium between the celebrities and their followers. They are acutely tailored to create the most personalized and authentic fan experiences, one-on-one without the intervention of PR managers, agents and everyone that stands to gain (or lose) from allowing these unique and special interactions to occur.&nbsp;</p>\n<p>They allows our Stars to monetize each engagement with instant and 100% ROI for their time and effort.</p>\n<p>Their personal relationships will bring some of the biggest names from South-East Asia and the Indian sub-continent and allow anyone to place a special request for the Stars to record personlized video messages, advice, greetings or words of encouragement and inspiration for their friends, family, employees, colleagues or even promote their own brand and business for a fraction of the cost the celebrities charge for an instagram post.</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 6,
      name: 'Client 6',
      about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p><span style="font-size: 16px;">Our client is a leading digital wallet service in the Southeast Asia Region, where consumers can easily purchase, sell and secure assets like Ethereum, Bitcoin and Litecoin. The company was founded in 2014 and headquartered in Singapore.</span></p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 7,
      name: 'Client 7',
      about: '<p><strong>b. About Client:</strong></p>\n<p>Our Client is a Singapore-based startup that provides a smart online ordering system which enables F&amp;B business owners to manage their own take-away orders and grow their business. Since its platform launched in 2014, it is heating up the food delivery space, with over USD16 million worth of orders transacted!</p>\n<p>Unlike marketplaces, it is a cloud-based, e-commerce and orders management solution which caters specifically to the operations of F&amp;B businesses. Their solution is a unified, all-in-one online ordering system which funnels all orders to designated restaurants.</p>\n<p>Today, more than 1400 restaurants are their happy customers! As they strive to make their product the right fit for all, they want to empower all F&amp;B players to take control of their business through an all-in-one, integrated and cost-effective solution.</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 8,
      name: 'Client 8',
      about: '<p><strong><em>&nbsp;b. About Client:</em></strong></p><p>Our client is the first fully regulated platform in a major financial center to offer issuance, settlement, custody and secondary trading of digitized securities. Using blockchain and smart contracts as enabling technologies, they allow the issuance, investment and trading of fully-regulated digitized securities with structures customizable to each issuer. </p><p>Through their platform, they provide liquidity and access to previously inaccessible parts of the capital market in a secure, compliant and cost-effective manner. They are fully licensed by the Monetary Authority of Singapore, with the Singapore Exchange and Heliconia (a fully owned subsidiary of Temasek) as key investors. </p><p>They are seeking a Blockchain Developer to join their Development team. They aim to constantly innovate, discover and implement state-of-art technology for our platform. If you love working with innovative technology, they would love to speak with you.</p><p>They have an existing team of experience Blockchain developers based in Singapore including a Vietnamese senior developer staying in Singapore and also a tech team based in China.</p><p>They are looking for a Blockchain Research Engineer to join their Vietnam team (bases on Hanoi) or relocate to Singapore.</p>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 9,
      name: 'Client 9',
      about: '<p><strong><em>&nbsp;b. About Client: </em></strong></p><p>Our client is an online marketplace for Advertisement spaces named Airvert.</p><p>What is so cool about them is that they want to reinvent the way people see and use spaces, turning all the Available Idle spaces into Rentable advertising space! Be creative and you will be able convert those spaces for advertisement placements! They hope that through Airvert, everyone can have better use of idle space and access to affordable marketing!&nbsp;</p><p>Airvert is a platform for anyone to list available “AIR-spaces” and for anyone to book them for advertisement placements. What is an AIR-space? It is any public facing space. Cafes interior, tables, shop windows, car fleets, toilets.. You name it!</p><p>They are a marketplace that allows businesses (AIR-space Owners) to maximize underutilised spaces they have, to help businesses (Advertisers) with the opportunity to reach out to their customers at a more affordable cost. Airvert is platform that creates an ecosystem for Outdoor Advertising Display spaces, in all location, sizes and forms; From-for businesses of all spectrum. A fuss free way to list AIR-spaces or book them for your advertising needs.</p><p>Airvert is created by a Tech Entrepreneur, and a marketing devotee who believes that no business is sustainable alone, or without being connected (to their customers via advertising). They saw technology as the key to the answer. Airvert aims to be the solution that will connect businesses and create a ecosystem that:</p><p>- Redefine how spaces can be used to generate additional Revenue; and</p><p>- Redesigns the way how Out of Home Advertisements are done.</p><p>They hope to empower businesses of all sizes to stay competitive in the market place by fostering mutual support amongst non competing businesses through win-win opportunities ; everyone gets more value with the available existing resources.</p><p><img src="https://data-main.basecdn.net/201904/sys1002/hiring/04/15/a6/7b/a3/7e/ae/e58f3deeff0c0dca354bc4244ec71d9c/7420f2e5191e3bc831be9ec502fca83c_130997_SFH2H84GJV476.jpg" alt="1.jpg"></p>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 10,
      name: 'Client 10',
      about: '<p><strong>b. About Client:</strong></p>\n<p>Our client is a Singapore based crypto currency exchange that providing fiat to crypto and crypto to crypto exchange. They aim to be the first exchange to let you trade Blockchain ideas, knowledge and values.&nbsp;</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 11,
      name: 'Client 11',
		  about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p>Our client is the go-to digital-treasury platform that enables Customers in Asia to efficiently manage and execute international payments and collections. They enable intra-Asia and local-currency access, allowing them to manage and enhance their transactions, increase cost competitiveness, and gain valuable insights into their financial positions.&nbsp;</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 12,
      name: 'Client 12',
      about: '<p><strong>b. About Client:</strong></p><p>Our client is a Y-Combinator startup with venture funding from top VC firms (Initialized, Khosla Ventures) in Silicon Valley. We run a 7-week professional development program that helps Fellows - top-tier PhDs and experienced engineers - transition to full-time data roles in data science, data engineering and AI. </p><p>We are looking for a Mobile Lead to manage the development of our internal mobile communications apps, similar to Slack, that serve our community of Fellows.</p><img src="https://data-main.basecdn.net/201904/sys1002/hiring/02/09/97/1e/84/5d/3f/4c159ef815a9289ee926a1924059f953/eac90e6aed8a653505f7a71985e3442c_118701_NGJQQZKFFLV2V.jpeg" alt="jdphoto.jpeg"><br><br>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 13,
      name: 'Client 13',
      about: "<p><span style=\"color: rgb(0,0,0);\"><strong>b. About Client:</strong></span></p>\n<p style=\"text-align:start;\"><span style=\"color: rgb(0,0,0);font-family: sans-serif;\">Empire Diamonds was incepted in 2020 following the great success of its parent company Empire Treasures Pte Ltd. Empire Diamonds strives to acquire only the World's finest diamonds, displaying a remarkable collection that caters to all diamond enthusiasts in Asia. With our team of highly skilled jewellery designers and craftsmen, every diamond is meticulously crafted into classically elegant and unique masterpieces, ensuring that you will be the brightest star of the night. Empire diamonds is looking to build a marketplace for trading for diamonds and aims to become a leading diamond marketplace in Asia and the world.</span></p>\n",
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 14,
      name: 'Client 14',
      about: '<p><strong><em>b. About Client:</em></strong><br></p><p>Our client is a Singapore’s fastest growing mobile ordering, payment, and loyalty platform. They have a mission: <b>to make mobile ordering and payment the new way of life when dining out</b>. </p><p>Through their next-generation mobile point-of-sale (POS) that covers the entire customer ordering and payment process, they enhance customer experience, improve operating efficiency, and allow our merchants to stay connected with their customers and engage them anytime, anywhere. They launched their services in Singapore in 2018 and have since gained market share quickly while delivering best-in-class customer experience.&nbsp;</p><p>They are backed by some of the top-tier venture capitalist and entrepreneurs in the region, including the likes of East Ventures, Quest Ventures, Goh Yiping (ex-Matahari Mall chief product officer).</p>\r\n        <p><b>Top 3 Reasons to join them now:</b><br></p><ul><li>Opportunity to drive technical transformation using the latest framework and architectures.</li><li>Work on products that are currently adopted by users across Asia.</li><li>Attractive salary and great working environment.</li></ul><p><img src="https://data-main.basecdn.net/201904/sys1002/hiring/04/15/a6/7b/a3/7e/ae/e58f3deeff0c0dca354bc4244ec71d9c/7420f2e5191e3bc831be9ec502fca83c_130997_SFH2H84GJV476.jpg" alt="1.jpg"><br></p>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 15,
      name: 'Client 15',
      about: '<p><strong>b. About Client:</strong></p>\n<p>With our client website for business, SMEs can pay rent, salaries, invoices, and even corporate tax using the credit cards they already have in their wallet today. SMEs love this website because it works like a credit card, but pays like cash.</p>\n<p>It’s secure and easy to use platform reliably delivers payments to vendors while freeing up cash and providing access to interest free credit. Forget the delays and aggravations that come with traditional SME financing options. Schedule recurring payments, manage invoices, set payment reminders, and monitor payment status all from one dashboard.</p>\n<p>It’s never been easier for SMEs to meet monthly payment obligations while keeping cash available to fuel growth, bridge receivable gaps, and make immediate investment in the supplies, services, and expertise needed to drive a growing business forward.</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 16,
      name: 'Client 16',
      about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p>Our client was incepted in 2005 and it is a leading company in online gaming.</p>\n<p>They are looking to develop in-house high-tech online gaming solutions. They have one of the products already launched and the company is looking to hire motivated developers to continue developing future trends in gaming. </p>\n<p>This opportunity will give developers the chance to work on cutting edge technology in the online gaming sector. &nbsp;</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 17,
      name: 'Client 17',
      about: '<p><b>&nbsp;b. About Client:</b></p><p>Our client is a B2B digital treasury platform that allows businesses in Asia to efficiently manage their FX exposure, execute and collect international payments.</p><p>Our mission in client is to provide an end-to-end digital treasury solution for Asian businesses.&nbsp;&nbsp;</p><p>We aim to be the go-to business platform where businesses can virtually transact in local business environment through our coverage of key Asian local currencies with access anytime, anywhere. Our goal is to optimize manage global transactions for Asia-based business by enhancing liquidity while reducing time and cost of cross-border business operations.&nbsp;</p><br><img src="https://data-main.basecdn.net/201904/sys1002/hiring/04/13/28/e6/da/1d/42/f86dc48fbbae26098999234e6bf37b03/20e32c027a5ccb04636b69693391a51e_752709_ZMMRWULW5BHZN.jpg" alt="1.jpg"><br>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 18,
      name: 'Client 18',
      about: '<p><strong><em>&nbsp;b. About Client:</em></strong></p><p>Our client is a digital lending company that is revolutionizing access to financial products for millions of emerging consumers in Indonesia. They have developed the first digital data-driven credit underwriting and risk assessment platform to process consumer loan applications and determine their creditworthiness using its mobile app. Established in late 2016, they deployed its lending platform in Jakarta and surrounding cities, and they are about to enter a hyper-growth period. Expansion to the rest of Indonesia is expected to complete within a year. Our client is based in Jakarta and is backed by leading venture capital firms in Indonesia and Singapore. They are looking for a Senior Software Engineer with CAN-DO attitude to build systems that leverage massive amount of data to drive the company financial products ready for nationwide scale.</p>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 19,
      name: 'Client 19',
      about: "<h3><span style=\"font-size: 16px;\"><strong>b. About Client:</strong></span></h3>\n<p>Our client aspires to be an organisation that reflects the close communities that their product brings together and serves. They believe that in addition to hiring the right talent, having the right values and mindsets, can lead the organisation in the right direction for specialty coffee.</p>\n<p>Their employees for that matter, are the driving force of the organisation. Their business exists with the following in mind : offering a product or solution, running operations and consolidating our financial position. Yet, this is always underpinned by its people and technology. While coffee as a crop and commodity remains the same, the perception of what coffee can be, has been and will continue to be evolving. They're looking for people who bring fresh ideas from all areas, and work with a collaborative mindset in achieving a collective effort. Whatever your position here, we seek your contribution in taking the initiative and speaking out.</p>\n<p>Our client will always be a coffee company at heart. They hire a diverse range of people with a broad set of technical skills who are ready to make however small a difference, in the world of specialty coffee. With coffee being pervasive in all cultures, countries, languages, social classes - they seek to bring communities closer together, by connecting people with coffee. While they aim to make better coffee, they also aim to make coffee better.&nbsp;&nbsp;</p>\n",
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 20,
      name: 'Client 20',
      about: "<h3><span style=\"font-size: 16px;\"><strong>b. About Client:</strong></span></h3>\n<p><span style=\"font-size: 16px;\">Our client is an exciting early-stage start-up that is revolutionizing cognitive healthcare by commercializing head-based bio-sensing technology. With a mission to improve human cognitive functions, their pioneering work is at the intersection of breakthrough wearable sensing, signal processing, and machine learning. They’ve invented the world's first and most advanced sleep improvement system and brain-computer interface in comfortable form factors like headphones. Their ultimate goal is to give 50% of the world access to low-cost, continuous mobile healthcare solutions to accelerate progress towards achieving that objective.</span></p>\n",
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 21,
      name: 'Client 21',
		  about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p><span style="font-size: 16px;">Our client is a 2 years startup in digital marketing. They help businesses to achieve business goals and marketing performance through digital channels. The company deeply understand in digital advertising, riding on the trends of digitalization to keep developing better solution for their clients. They are in hot growth phase, with +200% Year-on-year, and +500% in number of campaigns.</span></p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 22,
      name: 'Client 22',
		  about: '<h3><span style="font-size: 16px;"><strong>b. About Client:</strong></span></h3>\n<p>Our client is in the business of delivering world class training, having conducted programming courses to over 8000 students since 2017. They aspire to empower their students, regardless of career status and background. They hire not individuals but team members. They seek highly effective collaborators and can pick apart even their own ideas to further a common goal.&nbsp;</p>\n<p>Their version of a great workplace is not just one comprised of free lunches; Their ideal workplace is a dream team in pursuit of ambitious objective key results. It is on such a team that you learn the most, perform your best, and grow the fastest.&nbsp;</p>\n<p>They are looking for a Software Engineer to join the team. You will be part of the engineering team that focuses on delivering and the development of their various technology solutions to ensure the best possible student experience. At the same time, you will get to learn and experience modern technologies.</p>\n',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      id: 23,
      name: 'Client 23',
      about: '</p><p><strong>b. About Client:</strong></p><p>Our client is a leading forex brokerage that offers  derivative products and services  across various markets globally. As part of their global expansion plans, they are  looking to expand their product and service offerings with the introduction of  fin tech revolutionary features that include the famed loyalty program and the implementation of their proprietary Social Trading software.</p><p>You will work as a Senior Web  Application Developer and report directly to the Chief Technology Officer.</p><p><b>c. Job overview</b>:</p><p>- You will be responsible for developing and maintaining client-facing and  back-end operation web applications, including testing and  documentation. </p><p>- Able to create technical design and data modelling while working alongside  designer to implement UI and UX designs, among other duties.</p><p>- Creating and consuming API to link up back-end  operation applications with trading platform</p><p>- Maintaining and support trading platform servers.</p><p>- Full software development life cycle for Social  trading platform in the pipeline.</p><p>- Chance and opportunity to learn and develop auto  trading system or indicators.</p><p>- Chance and opportunity to learn and develop  Android app to complement client-facing applications</p>',
      website: '',
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ]),
  down: (queryInterface, Sequelize) => queryInterface.bulkDelete('Client', null, {}),
};
